name: spanish_master
description: "A new Flutter project for Spanish learning with high-quality TTS."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # 私は、ソースコード単体で発音を完結させるためにこれを導入しました
  flutter_tts: ^4.2.2

  # 私は、将来的に広告を表示するためのパッケージも保持しました
  google_mobile_ads: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # 私は、mp3を使わない方針に切り替えたため、assetsの設定は削除しました。
  # これにより「フォルダが見つからない」というエラーを防ぎます。